#!/usr/bin/env bash
#
# Emits a gradient BMP image
#
# Author: Dave Eddy <dave@daveeddy.com>
# Date: July 29, 2025
# License: MIT

. ./lib/bmp || exit

debug() {
	echo '[debug]' "$@" >&2
}

make-bmp() {
	local width=$1
	local height=$2

	bmp-header "$width" "$height"
	local padding=$REPLY

	local r g b y x
	for ((y = 0; y < height; y++)); do
		for ((x = 0; x < width; x++)); do
			((r = x * 255 / width))
			((b = y * 255 / height))
			bmp-rgb "$r" 0 "$b"
		done
		debug "handled row $((y + 1))/$height"
		bmp-pad "$padding"
	done
}

main() {
	local width=400
	local height=400
	local output=out.bmp

	local OPTIND OPTARG opt
	while getopts 'w:h:o:' opt; do
		case "$opt" in
			w) width=$OPTARG;;
			h) height=$OPTARG;;
			o) output=$OPTARG;;
		esac
	done

	make-bmp "$width" "$height" > "$output" || exit
	echo "generated ${width}x$height image: $output"
}

main "$@"
